version: '2'
services:
  torclient:
    image: "akdv88/alpine-tor:torclient"
    container_name: torclient
    ports:
      - "9050:9050"
      - "9100:9100"
    mem_limit: 50000000
    restart: always
  pacmaker:
    image: "akdv88/alpine-tor:pacmaker"
    container_name: pacmaker
    depends_on:
      - torclient
    volumes:
      - pac:/pac
    mem_limit: 120000000
    restart: always
  lighttpd:
    image: "akdv88/alpine-tor:lighttpd"
    container_name: lighttpd
    depends_on:
      - pacmaker
    ports:
      - "80:80"
    volumes:
      - pac:/pac
    mem_limit: 10000000
    restart: always
volumes:
  pac:
